### ISSUE TITLE
Использование без отправки письма с паролем

### ISSUE THREAD

**Issue by Phenixoid** [vaizmanai/srvisit#1]
При использовании сервера были проблемы с рассылкой писем, содержащих пароли новых пользователей, по smtp. Поэтому:
1) была выключена генерация случайных паролей. Новый пользователь создаётся со стандартным паролем "0000". Далее, в веб-интерфейсе его можно изменить. (processing.go str 199)
`newProfile.Pass = "0000"`
2) отключена библиотека "net/smtp", отключен код отправки письма.  (processing.go str 7, 200-207)
`//"net/smtp"`
`/*
			msg := []byte("Subject: Information from reVisit\r\n\r\nYour password is " + newProfile.Pass + "\r\n")
			err := smtp.SendMail(options.ServerSMTP+":"+options.PortSMTP, smtp.PlainAuth("server", "iarshinsky", options.PassSMTP, options.ServerSMTP), options.LoginSMTP, []string{message.Messages[0]}, msg)
			if err != nil {
				logAdd(MESS_ERROR, id+" не удалось отправить письмо с паролем: "+fmt.Sprint(err))
				sendMessage(conn, TMESS_NOTIFICATION, "Не удалось отправить письмо с паролем!")
				return
			}*/`

**Comment by vaizmanai** [comment]
Сегодня добавлю опцию для переключения режима работы без отправки писем.

**Comment by vaizmanai** [comment]
Готово.

**Comment by hhrhhr** [comment]
А где искать эту опцию?

**Comment by vaizmanai** [comment]
> А где искать эту опцию?

```
if len(Options.ServerSMTP) > 0 {
	SendEmail(message.Messages[0], msg)
} else {
	newProfile.Pass = PredefinedPass
}
```

В коде вот такой кусок есть, судя по всему если не указывать адрес почтового сервера, то пароль будет "0000".
