### ISSUE TITLE
Обход NAT: как?

### ISSUE THREAD

**Issue by hhrhhr** [vaizmanai/srvisit#10]
Как именно реализован данный процесс: сервер является прокси, который прогоняет через себя весь трафик клиентов за NAT-ами или он делает что-то вроде Nat 2 Nat (как https://www.uvnc.com/addons/nat2nat.html, подключая клиентов друг к другу и не участвуя далее в обмене)?

**Comment by vaizmanai** [comment]
Сервер является третьей точкой и прогоняет трафик через себя.
